[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/Resume_Wei_Hsin_Chen.pdf"
  to = "/assets/Resume_Wei_Hsin_Chen.pdf"
  status = 301